-- TrustedSQL database schema
-- PostgreSQL 17.x compatible schema-only bootstrap script.
--
-- This script intentionally contains no benchmark data, no personal records,
-- no credentials, and no Supabase or pgvector extension internals. It creates
-- the core academic schema used by the TrustedSQL runtime/evaluator. Load
-- synthetic or reviewed data separately when reproducing paper experiments.

CREATE SCHEMA IF NOT EXISTS public;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'application_status_type') THEN
    CREATE TYPE public.application_status_type AS ENUM ('pending', 'approved', 'rejected');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_status_type') THEN
    CREATE TYPE public.student_status_type AS ENUM ('studying', 'dropped_out', 'graduated', 'suspended');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status_type') THEN
    CREATE TYPE public.user_status_type AS ENUM ('active', 'inactive', 'blocked');
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.application_types (
  type_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type_name varchar(100) NOT NULL,
  category varchar(50) NULL,
  description text NULL,
  CONSTRAINT application_types_pkey PRIMARY KEY (type_id),
  CONSTRAINT application_types_type_name_key UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS public.campuses (
  campus_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campus_name varchar(100) NOT NULL,
  address varchar(255) NULL,
  CONSTRAINT campuses_pkey PRIMARY KEY (campus_id)
);

CREATE TABLE IF NOT EXISTS public.classes (
  class_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class_name varchar(50) NOT NULL,
  CONSTRAINT classes_class_name_key UNIQUE (class_name),
  CONSTRAINT classes_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.courses (
  course_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_code varchar(20) NOT NULL,
  syllabus_id_system varchar(50) NULL,
  course_name_en varchar(255) NOT NULL,
  course_name_vn varchar(255) NULL,
  no_credit int2 NOT NULL,
  time_allocation varchar(100) NULL,
  description text NULL,
  min_avg_mark_to_pass float8 DEFAULT 5.0 NULL,
  decision_no varchar(100) NULL,
  is_approved bool DEFAULT false NULL,
  approved_date date NULL,
  is_active bool DEFAULT true NULL,
  CONSTRAINT courses_course_code_key UNIQUE (course_code),
  CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.departments (
  dep_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dep_code varchar(10) NOT NULL,
  dep_name varchar(150) NOT NULL,
  CONSTRAINT departments_dep_code_key UNIQUE (dep_code),
  CONSTRAINT departments_pkey PRIMARY KEY (dep_id)
);

CREATE TABLE IF NOT EXISTS public.permissions (
  permission_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  permission_name varchar(150) NOT NULL,
  CONSTRAINT permissions_permission_name_key UNIQUE (permission_name),
  CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles (
  role_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_name varchar(150) NOT NULL,
  CONSTRAINT roles_pkey PRIMARY KEY (role_id),
  CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.course_clos (
  clo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id int4 NULL,
  clo_name varchar(50) NULL,
  description text NULL,
  CONSTRAINT course_clos_pkey PRIMARY KEY (clo_id),
  CONSTRAINT course_clos_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.course_grading_categories (
  category_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id int4 NULL,
  category_name varchar(100) NULL,
  weight float8 NULL,
  question_type text NULL,
  grading_guide text NULL,
  note text NULL,
  CONSTRAINT course_grading_categories_pkey PRIMARY KEY (category_id),
  CONSTRAINT course_grading_categories_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.course_materials (
  material_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id int4 NULL,
  material_description text NULL,
  author varchar(255) NULL,
  publisher varchar(255) NULL,
  is_main_material bool DEFAULT false NULL,
  is_online bool DEFAULT false NULL,
  CONSTRAINT course_materials_pkey PRIMARY KEY (material_id),
  CONSTRAINT course_materials_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.course_sessions (
  session_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  course_id int4 NULL,
  session_no int2 NULL,
  topic text NULL,
  learning_teaching_type varchar(50) NULL,
  student_tasks text NULL,
  clo_mapping text NULL,
  CONSTRAINT course_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT course_sessions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.majors (
  major_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  major_code varchar(20) NOT NULL,
  major_name varchar(150) NOT NULL,
  dep_id int4 NULL,
  CONSTRAINT majors_major_code_key UNIQUE (major_code),
  CONSTRAINT majors_pkey PRIMARY KEY (major_id),
  CONSTRAINT majors_dep_id_fkey FOREIGN KEY (dep_id) REFERENCES public.departments(dep_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.narrow_majors (
  narrow_major_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  narrow_major_code varchar(20) NOT NULL,
  narrow_major_name varchar(150) NOT NULL,
  major_id int4 NULL,
  CONSTRAINT narrow_majors_narrow_major_code_key UNIQUE (narrow_major_code),
  CONSTRAINT narrow_majors_pkey PRIMARY KEY (narrow_major_id),
  CONSTRAINT narrow_majors_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(major_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rolepermission (
  role_id int4 NOT NULL,
  permission_id int4 NOT NULL,
  CONSTRAINT rolepermission_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT rolepermission_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(permission_id) ON DELETE CASCADE,
  CONSTRAINT rolepermission_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.users (
  user_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username varchar(50) NOT NULL,
  gmail varchar(255) NOT NULL,
  "password" varchar(150) DEFAULT '123456789'::character varying NULL,
  fullname varchar(100) NULL,
  user_gender varchar(10) NULL,
  user_dob date NULL,
  phone_number varchar(15) NULL,
  user_address varchar(255) NULL,
  campus_id int4 NULL,
  status public.user_status_type DEFAULT 'active'::public.user_status_type NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
  CONSTRAINT users_gmail_key UNIQUE (gmail),
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_username_key UNIQUE (username),
  CONSTRAINT users_campus_id_fkey FOREIGN KEY (campus_id) REFERENCES public.campuses(campus_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.curriculum_frameworks (
  framework_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  framework_code varchar(50) NOT NULL,
  framework_name_vn varchar(255) NULL,
  framework_name_en varchar(255) NULL,
  description text NULL,
  decision_no varchar(100) NULL,
  major_id int4 NULL,
  narrow_major_id int4 NULL,
  batch varchar(10) NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
  CONSTRAINT curriculum_frameworks_framework_code_key UNIQUE (framework_code),
  CONSTRAINT curriculum_frameworks_pkey PRIMARY KEY (framework_id),
  CONSTRAINT curriculum_frameworks_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(major_id),
  CONSTRAINT curriculum_frameworks_narrow_major_id_fkey FOREIGN KEY (narrow_major_id) REFERENCES public.narrow_majors(narrow_major_id)
);

CREATE TABLE IF NOT EXISTS public.curriculum_subjects (
  framework_id int4 NOT NULL,
  course_id int4 NOT NULL,
  semester_no int2 NULL,
  pre_requisite text NULL,
  CONSTRAINT curriculum_subjects_pkey PRIMARY KEY (framework_id, course_id),
  CONSTRAINT curriculum_subjects_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE,
  CONSTRAINT curriculum_subjects_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.curriculum_frameworks(framework_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.lecturers (
  lecturer_id int4 NOT NULL,
  dep_id int4 NULL,
  CONSTRAINT lecturers_pkey PRIMARY KEY (lecturer_id),
  CONSTRAINT lecturers_dep_id_fkey FOREIGN KEY (dep_id) REFERENCES public.departments(dep_id) ON DELETE SET NULL,
  CONSTRAINT lecturers_lecturer_id_fkey FOREIGN KEY (lecturer_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.plos (
  plo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  framework_id int4 NULL,
  plo_code varchar(20) NULL,
  plo_name varchar(255) NULL,
  description text NULL,
  CONSTRAINT plos_pkey PRIMARY KEY (plo_id),
  CONSTRAINT plos_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.curriculum_frameworks(framework_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.students (
  student_id int4 NOT NULL,
  student_code varchar(20) NOT NULL,
  batch varchar(10) NULL,
  major_id int4 NULL,
  narrow_major_id int4 NULL,
  start_date date NULL,
  end_date date NULL,
  status public.student_status_type DEFAULT 'studying'::public.student_status_type NULL,
  framework_id int4 NULL,
  CONSTRAINT students_pkey PRIMARY KEY (student_id),
  CONSTRAINT students_student_code_key UNIQUE (student_code),
  CONSTRAINT students_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.curriculum_frameworks(framework_id) ON DELETE SET NULL,
  CONSTRAINT students_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(major_id),
  CONSTRAINT students_narrow_major_id_fkey FOREIGN KEY (narrow_major_id) REFERENCES public.narrow_majors(narrow_major_id),
  CONSTRAINT students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.userrole (
  user_id int4 NOT NULL,
  role_id int4 NOT NULL,
  CONSTRAINT userrole_pkey PRIMARY KEY (user_id, role_id),
  CONSTRAINT userrole_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE CASCADE,
  CONSTRAINT userrole_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.application (
  application_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id int4 NOT NULL,
  type_id int4 NOT NULL,
  reason text NULL,
  file_url varchar(255) NULL,
  status public.application_status_type DEFAULT 'pending'::public.application_status_type NULL,
  process_note text NULL,
  processed_by int4 NULL,
  create_date timestamp DEFAULT CURRENT_TIMESTAMP NULL,
  time_response timestamp NULL,
  CONSTRAINT application_pkey PRIMARY KEY (application_id),
  CONSTRAINT application_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id) ON DELETE CASCADE,
  CONSTRAINT application_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(user_id) ON DELETE SET NULL,
  CONSTRAINT application_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.application_types(type_id)
);

CREATE TABLE IF NOT EXISTS public.classcourse (
  class_course_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class_id int4 NOT NULL,
  course_id int4 NOT NULL,
  lecturer_id int4 NOT NULL,
  semester varchar(10) NOT NULL,
  CONSTRAINT classcourse_pkey PRIMARY KEY (class_course_id),
  CONSTRAINT classcourse_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(class_id),
  CONSTRAINT classcourse_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id),
  CONSTRAINT classcourse_lecturer_id_fkey FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(lecturer_id)
);

CREATE TABLE IF NOT EXISTS public.enrollments (
  enrollment_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  student_id int4 NOT NULL,
  class_course_id int4 NOT NULL,
  average float8 DEFAULT 0 NULL,
  status varchar(50) NOT NULL,
  CONSTRAINT enrollments_pkey PRIMARY KEY (enrollment_id),
  CONSTRAINT enrollments_student_class_key UNIQUE (student_id, class_course_id),
  CONSTRAINT enrollments_class_course_id_fkey FOREIGN KEY (class_course_id) REFERENCES public.classcourse(class_course_id) ON DELETE CASCADE,
  CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.grade_details (
  grade_detail_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  enrollment_id int4 NOT NULL,
  category_id int4 NOT NULL,
  grade_value float8 DEFAULT 0 NOT NULL,
  "comment" text NULL,
  CONSTRAINT grade_details_enrollment_category_key UNIQUE (enrollment_id, category_id),
  CONSTRAINT grade_details_pkey PRIMARY KEY (grade_detail_id),
  CONSTRAINT grade_details_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.course_grading_categories(category_id) ON DELETE CASCADE,
  CONSTRAINT grade_details_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(enrollment_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.schedules (
  schedule_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  class_course_id int4 NOT NULL,
  start_time timestamp NOT NULL,
  end_time timestamp NOT NULL,
  room varchar(50) NOT NULL,
  slot int2 NOT NULL,
  CONSTRAINT schedules_pkey PRIMARY KEY (schedule_id),
  CONSTRAINT schedules_class_course_id_fkey FOREIGN KEY (class_course_id) REFERENCES public.classcourse(class_course_id)
);

CREATE TABLE IF NOT EXISTS public.attendance (
  enrollment_id int4 NOT NULL,
  schedule_id int4 NOT NULL,
  status varchar(50) NOT NULL,
  CONSTRAINT attendance_pkey PRIMARY KEY (enrollment_id, schedule_id),
  CONSTRAINT attendance_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(enrollment_id),
  CONSTRAINT attendance_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(schedule_id)
);
